export enum QuantityTypes{
  TABLETS = "Tablets",
  BOTTLES = "Bottles",
  BLISTER_PACKS = "Blister Packs",
  STRIPS = "Strips",
  BOXES = "Boxes",
  CAPSULES = "Capsules",
  CAPLETS = "Caplets",
  SACHETS = "Sachets",
  JARS = "Jars",
  STICK_PACKS = "Stick Packs",
  AMPOULES = "Ampoules",
  VIALS = "Vials",
  PRE_FILLED_SYRINGES = "Pre-filled Syringes",
  UNIT_DOSE_CUPS = "Unit-dose Cups",
  SINGLE_DOSE_PACKETS = "Single-dose Packets",
  TUBES = "Tubes",
  TUBS = "Tubs",
  INDIVIDUAL_PATCHES = "Individual Patches",
  PRE_FILLED_APPLICATORS = "Pre-filled Applicators",
  CANISTERS = "Canisters",
  METERED_DOSE_INHALERS = "Metered Dose Inhalers",
  DRY_POWDER_INHALERS = "Dry Powder Inhalers",
  NEBULIZER_SOLUTIONS="Nebulizer Solutions"
}